version: "3"

services:
  influxdb:
    image: influxdb:1.8.5
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb 
    restart: on-failure

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    volumes:
      - ./custom_grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,briangann-gauge-panel,vonage-status-panel,neocat-cal-heatmap-panel
    restart: on-failure

volumes:
  influxdb:
  grafana:
